/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts` (hash: auto+kv)
interface __BaseEnv_Env {
	BUYER_PRIVATE_KEY: string;
	BUYER_ADDRESS: string;
	TOLLBOOTH_MCP: DurableObjectNamespace<import("./src/index").TollboothMCP>;
	tollbooth_cache: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TollboothMCP";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUYER_PRIVATE_KEY" | "BUYER_ADDRESS">> {}
}
