/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 2c47e863a4da599c8b62f34c8216c3f2)
interface __BaseEnv_Env {
	tollbooth_cache: KVNamespace;
	RECEIPTS: KVNamespace;
	ASSETS: Fetcher;
	BUYER_PRIVATE_KEY: string;
	BUYER_ADDRESS: string;
	MAINNET_BUYER_PRIVATE_KEY: string;
	MAINNET_BUYER_ADDRESS: string;
	TOLLBOOTH_MCP: DurableObjectNamespace<import("./src/index").TollboothMCP>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TollboothMCP";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUYER_PRIVATE_KEY" | "BUYER_ADDRESS" | "MAINNET_BUYER_PRIVATE_KEY" | "MAINNET_BUYER_ADDRESS">> {}
}
